"push ds \n"
        "pop es \n"
        "mov esi, offset input_str \n"
        "mov edi, offset output_str \n"
        "operation: \n"
        "lodsb \n"
            "cmp al, 32 \n"
            "jne first \n"
            "stosb \n"
            "jne final \n"

            "first: \n"
            "cmp al, 48 \n"
            "jb final \n"
            "cmp al, 47 \n"
            "ja second \n"
            "stosb \n"
           "jmp final \n"

            "second: \n"
            "cmp al, 128 \n"
            "jb final \n"
            "cmp al, 175 \n"
            "ja third \n"
            "stosb \n"
            "jmp final \n"

            "third: \n"
            "cmp al, 224 \n"
            "jb final \n"
            "cmp al, 241 \n"
            "ja final \n"
            "stosb \n"
            "jmp final \n"
            "final: \n"
        "mov ecx, '\0' \n"
            "cmp ecx, [esi] \n"
            "je exit \n"
        "jmp operarion \n"
            "exit: \n"
